services:
  database:
    image: postgres:16
    container_name: bdr_project_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
